---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    author: vamshi
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
...